definitions:
  dto.LoginDto:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.MerchantsDto:
    properties:
      createDate:
        $ref: '#/definitions/entity.JsonTime'
        type: object
      creator:
        type: integer
      delFlag:
        type: integer
      deptId:
        type: integer
      email:
        type: string
      gender:
        type: integer
      headUrl:
        type: string
      id:
        type: integer
      mobile:
        type: string
      name:
        type: string
      password:
        type: string
      pid:
        type: integer
      pids:
        type: string
      realName:
        type: string
      remark:
        type: string
      sort:
        type: integer
      status:
        type: integer
      superAdmin:
        type: integer
      updateDate:
        type: string
      updater:
        type: integer
      userId:
        type: integer
      username:
        type: string
      verifield:
        type: integer
    type: object
  entity.JsonTime:
    $ref: '#/definitions/time.Time'
  entity.SysDept:
    properties:
      createDate:
        example: "2020-05-27"
        type: string
      creator:
        type: integer
      delFlag:
        type: integer
      id:
        type: integer
      name:
        type: string
      pid:
        type: integer
      pids:
        type: string
      sort:
        type: integer
      updateDate:
        example: "2020-05-27"
        type: string
      updater:
        type: integer
    type: object
  entity.SysRole:
    properties:
      createDate:
        example: "2020-05-27"
        type: string
      creator:
        type: integer
      delFlag:
        type: integer
      deptId:
        type: integer
      id:
        type: integer
      name:
        type: string
      remark:
        type: string
      updateDate:
        example: "2020-05-27"
        type: string
      updater:
        type: integer
    type: object
  entity.SysUser:
    properties:
      createDate:
        $ref: '#/definitions/entity.JsonTime'
        type: object
      creator:
        type: integer
      delFlag:
        type: integer
      deptId:
        type: integer
      email:
        type: string
      gender:
        type: integer
      headUrl:
        type: string
      mobile:
        type: string
      password:
        type: string
      realName:
        type: string
      remark:
        type: string
      status:
        type: integer
      superAdmin:
        type: integer
      updateDate:
        type: string
      updater:
        type: integer
      userId:
        type: integer
      username:
        type: string
      verifield:
        type: integer
    type: object
  gin.H:
    additionalProperties: true
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: 1503780117@qq.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /admin/addRole:
    post:
      consumes:
      - application/json
      description: 新增角色
      parameters:
      - description: 角色
        in: body
        name: SysRole
        required: true
        schema:
          $ref: '#/definitions/entity.SysRole'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - ApiKeyAuth: []
  /dept/add:
    post:
      consumes:
      - application/json
      description: 新增组织机构
      parameters:
      - description: 组织
        in: body
        name: sysDept
        required: true
        schema:
          $ref: '#/definitions/entity.SysDept'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - ApiKeyAuth: []
  /dept/check/{id}:
    put:
      consumes:
      - application/json
      description: 审核通过
      parameters:
      - description: 商户申请人id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - ApiKeyAuth: []
  /dept/verify:
    get:
      consumes:
      - application/json
      description: 查询待审核的组织
      parameters:
      - description: 当前页数
        in: query
        name: pageNo
        required: true
        type: integer
      - description: 每页数据
        in: query
        name: pageSize
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - ApiKeyAuth: []
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: loginDto
        in: body
        name: loginDto
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
  /merchants/register:
    post:
      consumes:
      - application/json
      description: 商户注册申请
      parameters:
      - description: MerchantsDto
        in: body
        name: MerchantsDto
        required: true
        schema:
          $ref: '#/definitions/dto.MerchantsDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
  /register:
    post:
      consumes:
      - application/json
      description: 用户户注册
      parameters:
      - description: sysUser
        in: body
        name: sysUser
        required: true
        schema:
          $ref: '#/definitions/entity.SysUser'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
  /user/logout:
    post:
      consumes:
      - application/json
      description: 用户退出
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
